# Generated by Django 4.2.7 on 2023-12-03 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeartDiseasePredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('sex', models.IntegerField(default=0)),
                ('cp', models.IntegerField(default=0)),
                ('trestbps', models.FloatField(default=0)),
                ('chol', models.FloatField(default=0)),
                ('fbs', models.IntegerField(default=0)),
                ('restecg', models.IntegerField(default=0)),
                ('thalach', models.FloatField(default=0)),
                ('exang', models.IntegerField(default=0)),
                ('oldpeak', models.FloatField(default=0)),
                ('slope', models.IntegerField(default=0)),
                ('ca', models.IntegerField(default=0)),
                ('thal', models.IntegerField(default=0)),
                ('prediction', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiabetesPredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField(default=0)),
                ('glucose', models.IntegerField(default=0)),
                ('blood_pressure', models.IntegerField(default=0)),
                ('skin_thickness', models.IntegerField(default=0)),
                ('insulin', models.IntegerField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('diabetes_pedigree_function', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('prediction', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
